### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by mag0** [jaredly/treed#16]
Hi, 
I cant run 'make all':
<pre>
make: *** No rule to make target `all'.  Stop.
</pre>

My 'npm install' shows:
<pre>
npm WARN package.json Dependency 'reactify' exists in both dependencies and devDependencies, using 'reactify@^0.14.0' from dependencies
npm WARN package.json superagent-browserify@0.0.2 No repository field.
</pre>

**Comment by mag0** [comment]
If someone could send the "index.html" generated in the Demo folder, i would apreciate.

**Comment by jaredly** [comment]
I updated the demos (and readme). Building is now done via webpack.
